# Generated by Django 4.0 on 2021-12-16 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Quesiton',
            new_name='Question',
        ),
    ]
